import env from "@/config/env";

const ORTHANC_URL = env.ORTHANC_URL ?? "http://localhost";
const ORTHANC_HTTP_PORT = env.ORTHANC_HTTP_PORT ?? "8042";
const ORTHANC_USERNAME = env.ORTHANC_USERNAME ?? "orthanc";
const ORTHANC_PASSWORD = env.ORTHANC_PASSWORD ?? "orthanc";
const ORTHANC_BASE_URL = `${ORTHANC_URL}:${ORTHANC_HTTP_PORT}`;
const ORTHANC_AUTH_HEADER = `Basic ${btoa(`${ORTHANC_USERNAME}:${ORTHANC_PASSWORD}`)}`;

export interface MWLWorklistItem {
    // Patient Info
    patientId: string; // PatientID / MRN
    patientName: string; // Nama lengkap
    patientBirthDate: string; // YYYY-MM-DD
    patientSex: "M" | "F" | "O";

    // Procedure Info
    accessionNumber: string; // PENTING: Unique identifier
    requestedProcedure: string; // Deskripsi pemeriksaan

    // Scheduled Step
    modality: string; // CT, MR, CR, DX, etc
    stationAETitle: string; // AE Title modality
    scheduledDate: Date; // Jadwal pemeriksaan
    scheduledStepId: string; // ID step
    scheduledStepDescription: string;

    // Optional: Referring Physician
    referringPhysician?: string;

    // Optional: Study Instance UID (auto-generate if empty)
    studyInstanceUID?: string;
}

/**
 * Convert JavaScript Date to DICOM Date (YYYYMMDD)
 */
export function toDicomDate(date: Date): string {
    const year = date.getFullYear();
    const month = `${date.getMonth() + 1}`.padStart(2, "0");
    const day = `${date.getDate()}`.padStart(2, "0");
    return `${year}${month}${day}`;
}

/**
 * Convert JavaScript Date to DICOM Time (HHMMSS)
 */
export function toDicomTime(date: Date): string {
    const hours = `${date.getHours()}`.padStart(2, "0");
    const minutes = `${date.getMinutes()}`.padStart(2, "0");
    const seconds = `${date.getSeconds()}`.padStart(2, "0");
    return `${hours}${minutes}${seconds}`;
}

/**
 * Convert name to DICOM Person Name format (FAMILY^GIVEN^MIDDLE)
 */
export function toDicomPersonName(name: string): string {
    // Simple: replace spaces with ^
    return name.trim().replace(/\s+/g, "^");
}

/**
 * Generate DICOM UID
 */
export function generateDicomUID(root: string = "1.2.826.0.1.3680043.8.498"): string {
    const timestamp = Date.now();
    const random = Math.floor(Math.random() * 1_000_000);
    return `${root}.${timestamp}.${random}`;
}

/**
 * Push worklist item ke Orthanc MWL
 */
export async function pushWorklistToOrthanc(item: MWLWorklistItem): Promise<{
    success: boolean;
    instanceId?: string;
    error?: string;
}> {
    try {
        const dicomDate = toDicomDate(item.scheduledDate);
        const dicomTime = toDicomTime(item.scheduledDate);
        const dicomBirthDate = item.patientBirthDate.replace(/-/g, ""); // YYYYMMDD
        const dicomPatientName = toDicomPersonName(item.patientName);

        // Create DICOM Worklist using Orthanc's /tools/create-dicom
        // Note: StudyInstanceUID will be auto-generated by Orthanc
        const body = {
            Tags: {
                // Patient Module
                PatientName: dicomPatientName,
                PatientID: item.patientId,
                PatientBirthDate: dicomBirthDate,
                PatientSex: item.patientSex,

                // Study Module (NO StudyInstanceUID for MWL!)
                AccessionNumber: item.accessionNumber,
                ReferringPhysicianName: item.referringPhysician || "",

                // Requested Procedure Module
                RequestedProcedureDescription: item.requestedProcedure,
                RequestedProcedureID: item.accessionNumber,

                // Scheduled Procedure Step Sequence
                ScheduledProcedureStepSequence: [
                    {
                        Modality: item.modality,
                        ScheduledStationAETitle: item.stationAETitle,
                        ScheduledProcedureStepStartDate: dicomDate,
                        ScheduledProcedureStepStartTime: dicomTime,
                        ScheduledProcedureStepID: item.scheduledStepId,
                        ScheduledProcedureStepDescription: item.scheduledStepDescription,
                        ScheduledPerformingPhysicianName: item.referringPhysician || "",
                        ScheduledProcedureStepStatus: "SCHEDULED",
                    },
                ],

                // Worklist specific
                SpecificCharacterSet: "ISO_IR 192", // UTF-8
            },
        };

        console.log("[MWL] Pushing worklist to Orthanc:", item.accessionNumber);

        const response = await fetch(`${ORTHANC_BASE_URL}/tools/create-dicom`, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                Authorization: ORTHANC_AUTH_HEADER,
            },
            body: JSON.stringify(body),
        });

        if (!response.ok) {
            const errorText = await response.text();
            console.error("[MWL] Orthanc error:", errorText);
            return {
                success: false,
                error: `Orthanc error: ${response.status} - ${errorText}`,
            };
        }

        const result = (await response.json()) as any;
        const instanceId = result.ID || result.InstanceId;

        console.log("[MWL] Worklist pushed successfully. Instance ID:", instanceId);

        return {
            success: true,
            instanceId,
        };
    } catch (error) {
        console.error("[MWL] Error pushing worklist:", error);
        return {
            success: false,
            error: error instanceof Error ? error.message : "Unknown error",
        };
    }
}

/**
 * Query worklist dari Orthanc by AccessionNumber
 */
export async function queryWorklistByAccession(accessionNumber: string): Promise<{
    success: boolean;
    data?: any;
    error?: string;
}> {
    try {
        // Search studies by accession number
        const response = await fetch(`${ORTHANC_BASE_URL}/tools/find`, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                Authorization: ORTHANC_AUTH_HEADER,
            },
            body: JSON.stringify({
                Level: "Study",
                Query: {
                    AccessionNumber: accessionNumber,
                },
                Expand: true,
            }),
        });

        if (!response.ok) {
            const errorText = await response.text();
            return {
                success: false,
                error: `Orthanc query error: ${response.status} - ${errorText}`,
            };
        }

        const results = await response.json();

        return {
            success: true,
            data: results,
        };
    } catch (error) {
        return {
            success: false,
            error: error instanceof Error ? error.message : "Unknown error",
        };
    }
}

/**
 * Delete worklist item dari Orthanc by instance ID
 */
export async function deleteWorklistFromOrthanc(instanceId: string): Promise<{
    success: boolean;
    error?: string;
}> {
    try {
        const response = await fetch(`${ORTHANC_BASE_URL}/instances/${instanceId}`, {
            method: "DELETE",
            headers: {
                Authorization: ORTHANC_AUTH_HEADER,
            },
        });

        if (!response.ok) {
            const errorText = await response.text();
            return {
                success: false,
                error: `Orthanc delete error: ${response.status} - ${errorText}`,
            };
        }

        console.log("[MWL] Worklist deleted successfully. Instance ID:", instanceId);

        return {
            success: true,
        };
    } catch (error) {
        return {
            success: false,
            error: error instanceof Error ? error.message : "Unknown error",
        };
    }
}
